name: Build WebUI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Cache Bun & Next.js
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-

      - name: Disable Next.js telemetry
        run: bunx next telemetry disable

      - name: Install dependencies
        run: bun install

      - name: Handle versioning
        run: |
          BRANCH="${GITHUB_REF##*/}"
          echo "Current branch: $BRANCH"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ "$BRANCH" = "dev" ]; then
            bun run release -- --prerelease dev --skip.changelog --skip.tag
            git push --follow-tags origin dev
          elif [ "$BRANCH" = "main" ]; then
            bun run release
            git push --follow-tags origin main
          fi

      - name: Build project
        run: bun run build

      - name: Rename output folder
        run: mv ./out ./www

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: www
          path: ./www
